### ISSUE TITLE
Investigate errors showing in console "TypeError: Invalid URL"

### ISSUE THREAD

**Issue by foolo** [zkemail/archive.prove.email#79]
On a fresh deployment, the following errors show in the console when accessing the site

![Screenshot_2024-04-19_18-41-55](https://github.com/zkemail/archive.prove.email/assets/667227/c41ff193-4200-4327-85e2-9e74e6946ab1)

```
 ✓ Ready in 3.3s
 ○ Compiling / ...
 ✓ Compiled / in 37.6s (3243 modules)
 ⨯ TypeError: Invalid URL
    at __webpack_require__ (/home/olof/archive.prove.email/dkim-lookup-app/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/session-provider.tsx:7:73)
    at (ssr)/./src/app/session-provider.tsx (/home/olof/archive.prove.email/dkim-lookup-app/.next/server/app/page.js:330:1)
    at __webpack_require__ (/home/olof/archive.prove.email/dkim-lookup-app/.next/server/webpack-runtime.js:33:42)
 ○ Compiling /api/auth/[...nextauth] ...
 ✓ Compiled /api/auth/[...nextauth] in 20.4s (3447 modules)
 ⨯ TypeError: Invalid URL
    at new URL (node:internal/url:796:36)
    at parseUrl (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.7_next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/utils/parse-url.js:12:18)
    at assertConfig (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.7_next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/assert.js:32:39)
    at AuthHandler (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.7_next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:90:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuthRouteHandler (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.7_next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:50:30)
    at async NextAuth._args$ (webpack-internal:///(rsc)/./node_modules/.pnpm/next-auth@4.24.7_next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:85:24)
    at async /home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63809
    at async eU.execute (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53964)
    at async eU.handle (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65062)
    at async doRender (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1543:40)
    at async DevServer.renderToResponseWithComponentsImpl (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1463:28)
    at async DevServer.renderPageComponent (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1856:24)
    at async DevServer.renderToResponseImpl (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1894:32)
    at async DevServer.pipeImpl (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:271:17)
    at async DevServer.handleRequestImpl (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:807:17)
    at async /home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:163:21)
    at async handleRequest (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:342:24)
    at async requestHandlerImpl (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:366:13)
    at async Server.requestListener (/home/olof/archive.prove.email/dkim-lookup-app/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:140:13) {
  code: 'ERR_INVALID_URL',
  input: ''
}
```

**Comment by hhuntaa** [comment]
i think it might be because youre using NEXTAUTH_URL="http://localhost:3000" in production or the url is wrong

**Comment by Divide-By-0** [comment]
> i think it might be because youre using NEXTAUTH_URL="http://localhost:3000" in production or the url is wrong

Hmm the URL we put is https://archive.prove.email -- what could be improved?
